version: '3.9'
services:

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - nginx
    environment:
      - DOMAIN=$DOMAIN
      - EMAIL=$EMAIL
  
  nginx:
    restart: always
    build: 
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
      - django_static:/var/www/static
      - django_media:/var/www/media
    depends_on:
      django:
        condition: service_healthy
    environment:
      - DOMAIN=$DOMAIN
  
  bot:
    restart: always
    build: 
      context: ./delivery_bot
    depends_on:
      django:
        condition: service_healthy
    environment:
      - APP_BASE_URL=$APP_BASE_URL
      - TOKEN=$TOKEN
      - API_URL=$API_URL
      - API_USER=$API_USER
      - API_PASSWORD=$API_PASSWORD
      - TZ=$TZ
      - TIME_START=$TIME_START
      - TIME_END=$TIME_END

  django:
    restart: always
    build:
      context: ./delivery
    volumes:
      - django_static:/var/www/static
      - django_media:/var/www/media
    depends_on:
      - postgre
    command: >
      sh -c "./delivery/wait-for-postgres.sh postgre &&
            gunicorn -w 3 --chdir ./ delivery.wsgi --bind 0.0.0.0:8000"
    healthcheck:
      test: curl --fail http://django:8000 || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    environment:
      - DOMAIN=$DOMAIN
      - SECRET_KEY=$SECRET_KEY
      - PG_HOST=$PG_HOST
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - TOKEN_ADMIN_GROUP=$TOKEN_ADMIN_GROUP
      - CHANEL=$CHANEL
  
  postgre:
    restart: always
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  certbot_conf:
  certbot_www:
  certbot_lib:
  db:
  django_static:
  django_media:
  