# Generated by Django 4.1.1 on 2022-10-21 09:09

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='ID пользователя telegram')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес доставки')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Пользователь телеграмм',
                'verbose_name_plural': 'Пользователи телеграмм',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создание')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновление')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.customerstg', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.price', verbose_name='Продукт')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orders')),
            ],
            options={
                'verbose_name': 'Содержимое заказа',
                'verbose_name_plural': 'Содержимое заказов',
            },
        ),
    ]
