# Generated by Django 4.1.1 on 2022-11-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_customerstg_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstg',
            name='tg_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='ID пользователя telegram'),
        ),
    ]
