# Generated by Django 4.1.1 on 2022-11-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='size',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Размер блюбда'),
        ),
        migrations.AlterField(
            model_name='products',
            name='aviable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Доступно для заказа'),
        ),
        migrations.AlterIndexTogether(
            name='price',
            index_together={('product', 'size')},
        ),
        migrations.AlterIndexTogether(
            name='products',
            index_together={('category', 'aviable')},
        ),
    ]
